- .github/workflows/build-main-devel.yml
- Dockerfile
- nuvlaedge/peripherals/bluetooth/__init__.py
- nuvlaedge/peripherals/bluetooth/__main__.py
- poetry.lock
- pyproject.toml
Closes nuvlaedge/peripheral-manager-bluetooth#9
> Add bluetooth peripheral bluetooth and pybluez build

- nuvlaedge/agent/common/nuvlaedge_common.py
- nuvlaedge/agent/common/util.py
- nuvlaedge/agent/monitor/components/nuvlaedge_info.py
- tests/agent/test_nuvlaedge_common.py
NuvlaEdge version is no longer extracted from an environmental Variable, instead is read from the package
> feat: changed NuvlaEdge version parsing, using importlib package 

- .github/workflows/build-main-devel.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- .gitignore
- README.md
- generate-requirements.sh
- extracted generation of requirements files
- provided documentation on how to run tests manually
Closes #78
> extract generation of requirements files

- Dockerfile
- nuvlaedge/agent/orchestrator/docker.py
- nuvlaedge/agent/orchestrator/kubernetes.py
- nuvlaedge/system_manager/common/container_runtime.py
- tests/agent/orchestrator/test_docker_client.py
- tests/system_manager/test_docker_client.py
> feat(agent): NE_IMAGE_* environment variables

- .github/workflows/validation.yml
> Add validation logs retrieval. Validation release 1.2.0

- Dockerfile
- scripts/credential-manager/k8s-cred-test.sh
- scripts/credential-manager/kubernetes-credential-manager.sh
> Merge credentials manager

- nuvlaedge/peripherals/modbus/__init__.py
> Fixes modbus discovery

- .coveragerc
- Dockerfile
- conf/example/security.toml
- nuvlaedge/agent/__init__.py
- nuvlaedge/common/nuvlaedge_config.py
- nuvlaedge/common/settings_parser.py
- nuvlaedge/security/__init__.py
- nuvlaedge/security/__main__.py
- nuvlaedge/security/constants.py
- nuvlaedge/security/patch/vulscan.nse
- nuvlaedge/security/security-entrypoint.sh
- nuvlaedge/security/security.py
- nuvlaedge/security/settings.py
- pyproject.toml
- tests/common/test_settings_parser.py
- tests/security/test_security.py
> Merge security component

- nuvlaedge/security/security.py
- tests/security/test_security.py
> Fix dataclass json serialization

- nuvlaedge/agent/monitor/components/geolocation.py
> Added exception catch to prevent errors from faulty server responses

- nuvlaedge/agent/agent.py
- nuvlaedge/agent/common/thread_handler.py
- nuvlaedge/agent/telemetry.py
- tests/agent/test_thread_handler.py
> Improved thread handling in telemetry class

- nuvlaedge/agent/orchestrator/kubernetes.py
This is a PR on top of the following PR:
- #142
> proposed changes for kubernetes image pull policy

- nuvlaedge/agent/orchestrator/kubernetes.py
Set the pull policy in the orchestrator
> Set the image pull policy

- Dockerfile
- Reduced the number of layers by combining RUN instructions.
- Reduced the image size by removing nmap-scripts and by compressing some executables.
> Dockerfile refactor: reduce Docker image size and number of layers

- poetry.lock
- pyproject.toml
Updates dependencies:
nuvla-api -> ^4.0.0
nuvla-job-engine -> ^4.0.5
> Update nuvla dependencies

- nuvlaedge/agent/settings.py
- nuvlaedge/common/constants.py
Closes: https://github.com/SixSq/tasklist/issues/3110
> fix: Update from v2.14.1 due to a variable naming miss-match

- nuvlaedge/common/constants.py
- nuvlaedge/peripherals/peripheral_manager_db.py
- tests/peripherals/test_peripheral_manager_db.py
Closes https://github.com/SixSq/tasklist/issues/3105
> fix: Fix error deleting peripherals

- nuvlaedge/agent/nuvla/client_wrapper.py
> fix(client_wrapper.py): Re-enable compression of data sent to Nuvla

- .github/workflows/build-main-devel.yml
- nuvlaedge/agent/__init__.py
- nuvlaedge/common/nuvlaedge_logging.py
> fix: Agent logging env configuration

- nuvlaedge/agent/__init__.py
> fix: Add thread tracer on signal SIGUSR1

- nuvlaedge/agent/common/util.py
- nuvlaedge/agent/orchestrator/docker.py
- nuvlaedge/agent/workers/monitor/components/network.py
- nuvlaedge/common/data_gateway.py
- tests/agent/monitor/components/test_network.py
- tests/common/test_data_gateway.py
> agent: get IPs with network_mode=host and allow data-gateway without system-manager

- nuvlaedge/agent/orchestrator/kubernetes.py
Closes https://github.com/SixSq/tasklist/issues/3298
Here is the new error message w/o the lengthy stack trace
```
[2024-10-02 13:18:57,324 - ERROR - nuvlaedge.agent.orchestrator.kubernetes/collect_container_metrics]: Failed listing pod metrics: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '430af0ab-48a5-4075-a145-4dc94822065f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '172e5b81-3b84-4138-9152-90d8c0a2c11b'
, 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b04ee873-ef37-41ec-a13c-94434f455c59', 'Date': 'Wed, 02 Oct 2024 13:18:57 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```
> don't fail on ApiException when listing Pods from metrics service

- .github/workflows/base-image.yml
- .github/workflows/build-main-devel.yml
- .github/workflows/bump-version.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- .github/workflows/validation.yml
- Dockerfile
- Dockerfile.base
- Dockerfile.slim-docker
- local-build.sh
- poetry.lock
- pyproject.toml
- sonar-project.properties
- tox.ini
> feat: upgrade base image to python 3.12 on alpine 3.20

- nuvlaedge/agent/nuvla/resources/infrastructure_service.py
- nuvlaedge/agent/orchestrator/docker.py
- nuvlaedge/agent/workers/vpn_handler.py
- poetry.lock
- pyproject.toml
- tests/agent/orchestrator/test_docker_client.py
- tests/agent/workers/test_vpn_handler.py
fix(docker): discover k3s even without compute-api.
fix(docker): remove new line character in vpn ip.
> fix(docker): discover k3s even without compute-api.

- nuvlaedge/agent/workers/vpn_handler.py
- tests/agent/workers/test_vpn_handler.py
> fix: Removed logs of the VPN credential exchange with Nuvla

- scripts/credential-manager/kubernetes-credential-manager.sh
* by default use NE UUID in CSR name to support multiple NEs on k8s cluster
* $CSR_NAME badly provided to wait for the issued certificate
See https://github.com/nuvlaedge/deployment/pull/130 for a detailed explanation.
> use NE UUID in CSR name to support multiple NEs on k8s cluster and fixes

- nuvlaedge/agent/orchestrator/kubernetes.py
- tests/agent/orchestrator/test_kubernetes_client.py
- tests/agent/utils/fake.py
Closes https://github.com/SixSq/tasklist/issues/3435
> fix(Kubernetes): detect manager nodes on new and old clusters

- nuvlaedge/agent/common/status_handler.py
- tests/agent/test_status_handler.py
Fixed a bug where the Status notes were not updated when the System Manager was removed after an update. Also added timeout checks (1H timeout) to status report
Closes https://github.com/SixSq/tasklist/issues/3302
> fix(Status Handler): Fix status handler bugs

- nuvlaedge/agent/agent.py
- nuvlaedge/agent/job.py
- nuvlaedge/agent/orchestrator/kubernetes.py
- tests/agent/orchestrator/test_kubernetes_client.py
- tests/agent/test_agent.py
- tests/agent/test_job.py
Closes https://github.com/SixSq/tasklist/issues/3238
> fix: don't fail agent in case same job ID is requested to be started

- nuvlaedge/agent/orchestrator/kubernetes.py
- nuvlaedge/peripherals/usb/go.mod
* fix: place job on the node along with NE when NE DB is needed by the job
* chore: update usb peripheral dependencies
Closes https://github.com/SixSq/tasklist/issues/3473
> 3473 run job on NE node
